---
- name: "build container with ansible"
  hosts: localhost
  tasks:
  - name: stop running ansible container
    command: docker stop ansible-container
    ignore_errors: yes

  - name: remove ansible-container
    command: docker rm ansible-container
    ignore_errors: yes
  
  - name: remove ansible-img
    command: docker rmi ansible-img
    ignore_errors: yes

  - name: build docker image from dockerfile
    command: docker build -t ansible-img .
  

  - name: create tag to image
    command: docker tag ansible-img abdallah02/car-website.img
  

  - name: run container from ansible-img
    command: docker run -d --name ansible-container -p 5000:80 ansible-img
